FROM node:current-alpine3.23
WORKDIR /account-service
COPY package*.json .
RUN npm install
COPY . .

EXPOSE 3000
CMD ["node", "app.js"]

# Install curl for healthcheck
RUN apk add --no-cache curl

# Delay healthcheck until app is ready
HEALTHCHECK --start-period=40s --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1
