FROM maven:3.9.6-eclipse-temurin-17 AS Base
WORKDIR /transaction-service
COPY . .
RUN mvn clean install -DskipTests

FROM eclipse-temurin:17-jre-alpine AS final
WORKDIR /transaction-service
COPY --from=Base /transaction-service/target/*.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

